### ISSUE TITLE
Infinite recursion avoided. Why?

### ISSUE THREAD

**Issue by bernex** [at-import/Sassy-Strings#10]
```
$shortName: str-replace($font, ' ', '');
```

Error:
WARNING: The string to be replaced is contained in the new string. Infinite recursion avoided.

' ' to '' ?

Also

```
$shortName: str-replace($font, 'a', 'b');
```

Same!

**Comment by KittyGiraudel** [comment]
I really need to rollback this repository.

**Comment by KittyGiraudel** [comment]
Should be all good now. Please, clone the repo again.

**Comment by bernex** [comment]
I don't see (

**Comment by KittyGiraudel** [comment]
You were using the unstable Sass version the repository has known. We rolled it back to Ruby, and it should work properly.

**Comment by strarsis** [comment]
I get this message with latest Saay-String (github master) 
and node-sass 3.4.2 and libsass 3.3.2.
It works without warnings with ruby sass though.

```
WARNING: The string to be replaced is contained in the new string. Infinite recursion avoided.
        on line 216 of node_modules/SassyStrings/dist/_SassyStrings.scss
```

Thank you and
With best regards
