### ISSUE TITLE
str-split

### ISSUE THREAD

**Issue by jamiebuilds** [at-import/Sassy-Strings#5]
Could `str-split` be reworked to accept a param to split it at a certain character? (like javascript?)

``` scss
str-split('foo.bar', '.')
=> (foo, bar)
```

**Comment by jamiebuilds** [comment]
Never mind, I just discovered str-explode, although I can't get it to work

**Comment by KittyGiraudel** [comment]
The latest version of `str-explode` is in SassyLists repository: https://github.com/Team-Sass/SassyLists/blob/master/stylesheets/SassyLists/_explode.scss. Although it's not merged in the Compass extension yet. Will be once Sass 3.3 got released.
