### ISSUE TITLE
str-replace : `str-index` improperly used.

### ISSUE THREAD

**Issue by mcaskill** [at-import/Sassy-Strings#8]
Hello!

The `str-index()` function is improperly used : it should be testing for "null", as per [Sass Reference](http://sass-lang.com/documentation/Sass/Script/Functions.html#str_index-instance_method), since we are querying for the _position_ of the first occurrence and not a _count_ of the number of occurrences.

``` sass
@if str-index($new, $old) != null {
    // ...
}
```

and

``` sass
@if $index != null and $new != $old {
    // ...
}
```

Cheers,

**Comment by KittyGiraudel** [comment]
Good point. Actually, it used to return `false` or `0` during alpha versions. I'll fix this.

**Comment by mcaskill** [comment]
Thank you for the rapid response!

And yes indeed, I found that out, about `false` and `0` being used in early versions, while digging around `str-index()`'s history.
